trigger:
  branches:
    include:
    - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: 'Use Python 3.7'
    
  - script: |
      python -m pip install --upgrade pip
      pip install --user --upgrade setuptools wheel twine
    displayName: 'Install dependencies'
  
  - script: |
      MLFARM_VERSION=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
      export MLFARM_VERSION="${MLFARM_VERSION//v}"
      echo "Version: ${MLFARM_VERSION}"
      python setup.py sdist bdist_wheel
      echo "Content:"
      ls dist
    displayName: 'Make archives'
  
  - script: |
      python -m twine upload --disable-progress-bar dist/*
    displayName: 'Upload to pypi'
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: $(mlfarm-pypi-token)